#! /bin/bash
# Copyright 2013 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Run startup scripts that should happen "Late" at boot.
# Run shutdown scripts that should happen as soon as the instances
# begin to power down.
#
# Do NOT "set -e"
declare -r SCRIPT=$1
declare -r SCRIPT_TYPE=$2

if [ -x /usr/bin/logger ]; then
  declare -r LOGGER=/usr/bin/logger
else
  declare -r LOGGER=/bin/logger
fi

LOG_CMD="${LOGGER} -t ${SCRIPT_TYPE}script -p daemon.info"

function log() {
  echo "$@" | ${LOG_CMD}
}

declare -r GOOGLE_ENVIRONMENT=/var/run/google.environment

function copy_and_run() {
  local source=$1
  local dest=$(mktemp)
  cat "${source}" >> "${dest}"
  chmod u+x "${dest}"
  log "Running ${SCRIPT_TYPE} script ${source}"
  "${dest}" 2>&1 | ${LOG_CMD}
  log "Finished running ${SCRIPT_TYPE} script ${source}"
  rm -f "${dest}"
}

if [[ -e "${SCRIPT}" ]]; then
  (
    [ -r ${GOOGLE_ENVIRONMENT} ] && source ${GOOGLE_ENVIRONMENT};
    copy_and_run "${SCRIPT}"
  )
fi
