#! /bin/bash
# Copyright 2013 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Run startup scripts that should happen "Late" at boot.
#
# Do NOT "set -e"
PATH=/sbin:/usr/sbin:/bin:/usr/bin:/usr/local/bin

declare -r STARTUP_SCRIPT=/var/run/google.startup.script

# Make sure all udev changes settle before running startup scripts.
udevadm settle

/usr/share/google/fetch_script ${STARTUP_SCRIPT} startup
/usr/share/google/run-scripts ${STARTUP_SCRIPT} startup
