#!/bin/bash
# Copyright 2016 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

### BEGIN INIT INFO
# Provides: expand-root
# Default-Start: 2 3 4 5
# Description: Expand the filesystem of the mounted root volume/partition to its maximum possible size
### END INIT INFO

device_path="/dev/sda1"
filesystem=$(blkid -s TYPE -o value $device_path)

case $filesystem in
  xfs)  xfs_growfs / ;;
  ext2) resize2fs $device_path ;;
  ext3) resize2fs $device_path ;;
  ext4) resize2fs $device_path ;;
  *)    echo "The filesystem $filesystem was not recognized. Unable to expand." ;;
esac
