#!/bin/sh
# Copyright 2016 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.
#
### BEGIN INIT INFO
# Provides:          google_shutdown_scripts
# Required-Start:
# Required-Stop:     $remote_fs $syslog docker kubelet
# Default-Start:
# Default-Stop:      0 6
# Short-Description: Google Compute Engine Shutdown Scripts
# Description:       Runs user specified shutdown scripts from metadata.
### END INIT INFO

NAME=google-shutdown-scripts
SCRIPTNAME=/etc/init.d/$NAME

# Load the rcS variables.
. /lib/init/vars.sh

#
# Function that stops the daemon/service.
#
do_stop()
{
  /usr/bin/google_metadata_script_runner --script-type shutdown > /dev/null
}

case "$1" in
  stop)
    do_stop
    ;;
  *)
    echo "Usage: $SCRIPTNAME stop" >&2
    exit 1
    ;;
esac

:
