#!/bin/sh
# Copyright 2016 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.
#
### BEGIN INIT INFO
# Provides:          google_network_setup
# Required-Start:    $all $google_instance_setup
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Google Compute Engine Network Setup
# Description:       Enables network interfaces on boot.
### END INIT INFO

NAME=google-network-setup
SCRIPTNAME=/etc/init.d/$NAME

# Load the rcS variables.
. /lib/init/vars.sh

#
# Function that starts the daemon/service.
#
do_start()
{
  /usr/bin/google_network_setup > /dev/null
}

case "$1" in
  start)
    do_start
    ;;
  *)
    echo "Usage: $SCRIPTNAME start" >&2
    exit 1
    ;;
esac

:
