#!/bin/sh
# Copyright 2016 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.
#
### BEGIN INIT INFO
# Provides:          $google_accounts_daemon
# X-Start-Before:    ssh
# Required-Start:    $local_fs $network $named $syslog $google_instance_setup
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Google Compute Engine Accounts Daemon
# Description:       Manages accounts from metadata SSH keys.
### END INIT INFO

# Do NOT "set -e".

NAME=google-accounts-daemon
DAEMON=/usr/bin/google_accounts_daemon
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

# Exit if the package is not installed.
[ -x "$DAEMON" ] || exit 0

# source function library
. /etc/init.d/functions

#
# Function that starts the daemon/service.
#
do_start()
{
  echo -n $"Starting $NAME:"
  daemon --pidfile $PIDFILE "$DAEMON &"
  touch $PIDFILE
  # workaround: when the system boots sometime the pid is not
  # ready righ away, wait a little
  usleep 100000
  PID="$(__pids_pidof "$DAEMON")"
  #echo "Saving PID" $PID " to " $PIDFILE
  if [ ! -z "$PID" ]; then
      echo $PID > $PIDFILE
  fi
  echo ""
}

#
# Function that stops the daemon/service.
#
do_stop()
{
  echo -n $"Stopping $NAME:"
  killproc -p $PIDFILE $DAEMON
  # Delete the pidfile when the daemon exits.
  rm -f $PIDFILE
  echo ""
}

case "$1" in
  start)
    do_start
    ;;
  stop)
    do_stop
    ;;
  status)
    status "$DAEMON" "$NAME" && exit 0 || exit $?
    ;;
  restart|force-reload)
    do_stop
    do_start
    ;;
  *)
    echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
    exit 1
    ;;
esac

:
