#!/bin/bash
# Dracut install script for EL6

inst_hook cmdline 99 "$moddir/growroot-dummy.sh"
inst_hook pre-mount 99 "$moddir/growroot.sh"

dracut_install awk
dracut_install growpart
dracut_install partx
dracut_install readlink
dracut_install sfdisk
dracut_install sgdisk
